### PR TITLE
Case corrections

### LINKED ISSUE #1: math.h
When MCP 3424 version 1.2 example sketch Multichannel is compiled in IDE 1.6.0 on linux it demands for Math.h (wich is included in MCP3424.h), but fails to found it, it works if i change to math.h.
Why the rest of the word don' care about capital letters?

### PR DESCRIPTION
**Pull request by kylegordon**
A couple of case corrections to fix #1

### CODE REVIEW

**Review by battosai30 — APPROVED** [review]

**Comment by kylegordon** [comment]
Did you mean to close it without merging the changes?

**Comment by battosai30** [comment]
No I approved it of course ! I'm not a github expert at all but files seem to be updated :)

Thanks

EDIT : or not, I already made somes of your correction months ago, but Math.h to math.h seems to don't have changed ... As I said I'm not a github expert xD

**Review by battosai30 — COMMENTED** [review]
It's OK

**Comment by kylegordon** [comment]
That's ok :-)

I'm looking at https://github.com/battosai30/MCP3424/blob/master/MCP3424.h and it seems to still have Math.h, and the one shot example still has the old entries too.

Did you 'git push' your changes from your local copy? That might be why it's not showing up on Github.

**Comment by battosai30** [comment]
Ok I don't know why but i reopened it, and I directly got a button "merge" ...

**Comment by kylegordon** [comment]
The mysteries of Github :-) 

All sorted now though, thank you!

**Pull request merged**
